<?php
// created: 2005-06-13 15:31:57
$sugar_config = array (
  'admin_export_only' => false,
  'cache_dir' => 'cache/',
  'calculate_response_time' => true,
  'create_default_user' => false,
  'date_formats' => 
  array (
    'Y-m-d' => '2006-12-23',
    'm-d-Y' => '12-23-2006',
    'd-m-Y' => '23-12-2006',
    'Y/m/d' => '2006/12/23',
    'm/d/Y' => '12/23/2006',
    'd/m/Y' => '23/12/2006',
  ),
  'dbconfig' => 
  array (
    'db_host_name' => 'mysql19.secureserver.net',
    'db_user_name' => 'spatiallink',
    'db_password' => 'SL1LDB97',
    'db_name' => 'spatiallink',
    'db_type' => 'mysql',
  ),
  'dbconfigoption' => 
  array (
    'persistent' => true,
    'autofree' => false,
    'debug' => 0,
    'seqname_format' => '%s_seq',
    'portability' => 0,
    'ssl' => false,
  ),
  'default_action' => 'index',
  'default_charset' => 'ISO-8859-1',
  'default_date_format' => 'Y-m-d',
  'default_language' => 'en_us',
  'default_module' => 'Home',
  'default_password' => '',
  'default_theme' => 'Sugar',
  'default_time_format' => 'H:i',
  'default_user_is_admin' => false,
  'default_user_name' => '',
  'disable_export' => false,
  'disable_persistent_connections' => 'false',
  'display_email_template_variable_chooser' => false,
  'display_inbound_email_buttons' => false,
  'dump_slow_queries' => false,
  'history_max_viewed' => 10,
  'host_name' => 'www.spatiallink.org',
  'import_dir' => 'cache/import/',
  'installer_locked' => true,
  'languages' => 
  array (
    'en_us' => 'US English',
  ),
  'large_scale_test' => false,
  'list_max_entries_per_page' => 20,
  'lock_default_user_name' => false,
  'log_dir' => '.',
  'log_file' => 'sugarcrm.log',
  'log_memory_usage' => false,
  'login_nav' => true,
  'require_accounts' => true,
  'rss_cache_time' => '10800',
  'save_query' => 'all',
  'session_dir' => '',
  'site_url' => 'http://www.spatiallink.org/gistools/manage/sa1',
  'slow_query_time_msec' => '100',
  'sugar_version' => '3.0c',
  'time_formats' => 
  array (
    'H:i' => '23:00',
    'h:ia' => '11:00pm',
    'h:iA' => '11:00PM',
    'H.i' => '23.00',
    'h.ia' => '11.00pm',
    'h.iA' => '11.00PM',
  ),
  'tmp_dir' => 'cache/xml/',
  'translation_string_prefix' => false,
  'unique_key' => '89bbabd74fbe8628bc720737c67d1be8',
  'upload_badext' => 
  array (
    0 => 'php',
    1 => 'php3',
    2 => 'php4',
    3 => 'php5',
    4 => 'pl',
    5 => 'cgi',
    6 => 'py',
    7 => 'asp',
    8 => 'cfm',
    9 => 'js',
    10 => 'vbs',
    11 => 'html',
    12 => 'htm',
  ),
  'upload_dir' => 'cache/upload/',
  'upload_maxsize' => 3000000,
  'verify_client_ip' => true,
);
?>
